easy_admin:
    site-name: 'Mise à jour'
    entities:
        Administrateur:
            class: App\Entity\Administrateur
            list:
                fields: ['Nom','Prenom']
                action:
                    - {name: 'edit', icon: 'pencil',  css class: 'btn btn-secondary', title: 'edit' }
                    - {name: 'delete', icon: 'trash', label: false, css class: 'btn btn-danger' }

        Utilisateur:
            class: App\Entity\Utilisateur
        Equipe:
            class: App\Entity\Equipe
        Jeu:
            class: App\Entity\Jeu


